# Generated by Django 3.1.3 on 2020-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('url', models.CharField(default='', max_length=25)),
                ('permissions', models.CharField(default='', max_length=25)),
                ('icon_class', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
