# Generated by Django 3.1.3 on 2020-11-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0003_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='mainmenu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.mainmenu'),
        ),
    ]
