# Generated by Django 3.1.7 on 2021-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cve_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='data_mode',
            field=models.CharField(blank=True, choices=[('', '------------'), ('text', 'From Text Data'), ('csv', 'From CSV'), ('api', 'From API  ')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_list',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
