# Generated by Django 3.1.7 on 2021-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211117_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='data_mode',
            field=models.CharField(blank=True, choices=[('', '------------'), ('text', 'From Text Data'), ('csv', 'From CSV'), ('api', 'From API  ')], default='no', max_length=100, null=True),
        ),
    ]
