# Generated by Django 3.1.7 on 2022-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211120_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='application_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='created_at',
            new_name='other_physician',
        ),
        migrations.RemoveField(
            model_name='library',
            name='data_mode',
        ),
        migrations.RemoveField(
            model_name='library',
            name='library_list',
        ),
        migrations.AddField(
            model_name='library',
            name='Alzheimer',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Arthritis',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Cancer',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='ClmAdmitDiagnosisCode',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Depression',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Diabetes',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='DiagnosisGroupCode',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Heartfailure',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='IschemicHeart',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='KidneyDisease',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='ObstrPulmonary',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Osteoporasis',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='RenalDiseaseIndicator',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='Stroke',
            field=models.CharField(choices=[('', '------'), ('1', 'Yes'), ('0', 'No')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='amount_reimbursed_as_inpatient',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='amount_reimbursed_as_outpatient',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_10',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_4',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_5',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_6',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_7',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_8',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='diagnosis_9',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '------'), ('0', 'Male'), ('1', 'Female')], default='no', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='no_of_days_admitted',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='no_of_days_for_claim',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='operating_physician',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='patient_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='physician_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_4',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_5',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='procedure_6',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='provider_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='race',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='total_deductable_paid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='total_deductable_paid_as_outpatient',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='library',
            name='total_insurance_reimbursed',
            field=models.IntegerField(default=None),
        ),
    ]
