# Generated by Django 3.1.7 on 2022-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220215_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='other_physician',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
