# Generated by Django 3.1.7 on 2022-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220215_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_fraudulent',
            field=models.BooleanField(default=False),
        ),
    ]
