# Generated by Django 3.1.7 on 2022-02-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220217_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='provider_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.provider'),
        ),
    ]
