# Generated by Django 3.1.7 on 2022-02-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220217_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='operating_physician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operating_physician', to='dashboard.physician'),
        ),
        migrations.AlterField(
            model_name='library',
            name='other_physician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='other_physician', to='dashboard.physician'),
        ),
    ]
